name = "dmv-learning"
main = "src/worker.js"
compatibility_date = "2026-05-25"
minify = true

[[kv_namespaces]]
binding = "LEARNING_KV"
id = "da996bc8b01b427f8ac4ca7826dfd68e"

[triggers]
crons = ["*/15 * * * *"]
